name: Build & Deploy (Scheduled)

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *" # every 30 minutes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          # ⚠️ کش npm را حذف کردیم چون lockfile نداری
      - run: npm install           # ← به‌جای npm ci (که lockfile می‌خواهد)
      - run: npm run fetch
        env:
          TRANSLATE_PROVIDER: ${{ secrets.TRANSLATE_PROVIDER }}
          DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }}
          GOOGLE_KEY: ${{ secrets.GOOGLE_KEY }}
          NEWSFA_DEFAULT_LANG: fa
      - run: npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
